### ISSUE TITLE
How to handle iframe?

### ISSUE THREAD

**Issue by tocha688** [reaz1995/ghost-cursor-playwright#15]
How to handle iframe?

**Comment by reaz1995** [comment]
The same way you handle it by playwright. There some googled ressources for you https://www.lambdatest.com/learning-hub/handling-iframes-in-playwright, hope that helps.
ghost-cursor-playwright script only simulate mouse movments.

**Comment by reaz1995** [comment]
The same way you handle it by playwright. There some googled ressources for you https://www.lambdatest.com/learning-hub/handling-iframes-in-playwright, hope that helps.
ghost-cursor-playwright script only simulate mouse movments.
