### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'isEqualNode')

### ISSUE THREAD

**Issue by galaczi** [reaz1995/ghost-cursor-playwright#16]
Hi, I am trying to click a button:
```
await cursor.actions.click({target: '#button', waitBeforeClick: [800, 3500]})
```
And getting this error:

```
TypeError: Cannot read properties of undefined (reading 'isEqualNode')
    at eval (eval at evaluate (:226:30), <anonymous>:4:42)
    at UtilityScript.evaluate (<anonymous>:228:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
```
Any idea why that happens?

**Comment by reaz1995** [comment]
probably your target is undefined as the error states

**Comment by galaczi** [comment]
It shouldn't be undefined. Playwright's ``page.fill`` finds it. ``cursor.getElemBoundingBox`` also finds it.

I can click with:
```
    const button = await cursor.getRandomPointInsideElem(await cursor.getElemBoundingBox('#button'))
    await page.mouse.click(button.x, button.y)
```

**Comment by reaz1995** [comment]
does await cursor.actions.move and await cursor.actions.click throw undefined?

**Comment by galaczi** [comment]
cursor.actions.move does not throw, only cursor.actions.click. Same selector.

**Comment by reaz1995** [comment]
ok try find path of the element you target -> inspector aim it then press Copy JS path, paste that path in curosr.actions.click target and let me know if that works

**Comment by galaczi** [comment]
You mean without document.querySelector, right? That wouldn't be a valid value for target. Yes, I have copied the selector from the browser as you suggested all along. It is found by playwright's locators, so it's definitely there. Maybe some kind of visibility or actionability test is the issue? locator.click() works though, so I don't think that should be an issue.

**Comment by reaz1995** [comment]
Check out the example in repo and see if you doesn't miss anything.
I messed around with the code now but everything works as intended.
The thing that throws you error is:
![image](https://github.com/user-attachments/assets/2a860480-2df9-43aa-807f-c51f027b8440)
write in the spawned page console
```
 window['mouseTarget']
```
this cant be undefined

**Comment by reaz1995** [comment]
Due to lack of activity i mark it as resolved.

**Comment by chrisloftus** [comment]
I'm getting the same error...
