### ISSUE TITLE
TypeError: createCursor is not a function

### ISSUE THREAD

**Issue by Mobeen-Ghaffar** [reaz1995/ghost-cursor-playwright#3]
const playwright = require('playwright')
const createCursor = require('ghost-cursor-playwright');
let browser = await playwright.firefox.launch({
            headless: false
        });
const context = await browser.newContext(
            {
            }
        );
const page = await context.newPage();
const cursor = await createCursor(page);

Issue: createCursor is not a function when trying to use this package. Any idea why I am getting this error?

**Comment by Mobeen-Ghaffar** [comment]
No worries figured out.
const createCursor = require('ghost-cursor-playwright').createCursor;

**Comment by reaz1995** [comment]
@Mobeen22-creator  just destruct
```javascript
const { createCursor } = require('ghost-cursor-playwright');
```

**Comment by Mobeen-Ghaffar** [comment]
> @Mobeen22-creator just destruct
> 
> ```js
> const { createCursor } = require('ghost-cursor-playwright');
> ```

Thanks issue resolved.
