### ISSUE TITLE
Possible to work with .net (c#)

### ISSUE THREAD

**Issue by brettwinters** [reaz1995/ghost-cursor-playwright#4]
Hi @reaz1995 - great work! this is exactly what I need, but how would I make it work with c#?

**Comment by reaz1995** [comment]
@brettwinters rewrite it to c# or expose bindings, im not familiar with c# so can't provide any help.

**Comment by brettwinters** [comment]
ok, I'll take a look under the hood of your code and see what I can do. Thanks for your quick reply!

**Comment by reaz1995** [comment]
If playwright bindings exposed for c# have same behaviour as for nodejs then you dont have to change much, probably just structure to match functions inting/calling, good luck

**Comment by brettwinters** [comment]
oh yes I see that you're using MouseHelper.js. I think it's possible to inject the js into the page using [this](https://playwright.dev/dotnet/docs/evaluating) or, as you say even use your code as it is....
